### ISSUE TITLE
pydantic_core.ValidationError: 4 validation errors for SubQuestionBundleList

### ISSUE THREAD

**Issue by aravindhp** [pchunduri6/rag-demystified#7]
I am getting the following error when running:

```
 rag-demystified   main U:3  python complex_qa.py 
⏳ Connect to EvaDB...
✅ Connected to EvaDB...
Creating vector store for Toronto...
01-03-2024 10:39:19 WARNING[executor_utils:executor_utils.py:handle_if_not_exists:0094] Table: Toronto_features already exists
WARNING:evadb.utils.logging_manager:Table: Toronto_features already exists
01-03-2024 10:39:19 WARNING[create_index_executor:create_index_executor.py:_create_evadb_index:0119] Index Toronto_index already exists. It will be updated on existing table.
WARNING:evadb.utils.logging_manager:Index Toronto_index already exists. It will be updated on existing table.
INFO:faiss.loader:Loading faiss with AVX2 support.
INFO:faiss.loader:Successfully loaded faiss with AVX2 support.
Successfully created vector store for Toronto.
Creating vector store for Chicago...
01-03-2024 10:39:19 WARNING[executor_utils:executor_utils.py:handle_if_not_exists:0094] Table: Chicago_features already exists
WARNING:evadb.utils.logging_manager:Table: Chicago_features already exists
01-03-2024 10:39:19 WARNING[create_index_executor:create_index_executor.py:_create_evadb_index:0119] Index Chicago_index already exists. It will be updated on existing table.
WARNING:evadb.utils.logging_manager:Index Chicago_index already exists. It will be updated on existing table.
Successfully created vector store for Chicago.
Creating vector store for Houston...
01-03-2024 10:39:19 WARNING[executor_utils:executor_utils.py:handle_if_not_exists:0094] Table: Houston_features already exists
WARNING:evadb.utils.logging_manager:Table: Houston_features already exists
01-03-2024 10:39:19 WARNING[create_index_executor:create_index_executor.py:_create_evadb_index:0119] Index Houston_index already exists. It will be updated on existing table.
WARNING:evadb.utils.logging_manager:Index Houston_index already exists. It will be updated on existing table.
Successfully created vector store for Houston.
Creating vector store for Boston...
01-03-2024 10:39:20 WARNING[executor_utils:executor_utils.py:handle_if_not_exists:0094] Table: Boston_features already exists
WARNING:evadb.utils.logging_manager:Table: Boston_features already exists
01-03-2024 10:39:20 WARNING[create_index_executor:create_index_executor.py:_create_evadb_index:0119] Index Boston_index already exists. It will be updated on existing table.
WARNING:evadb.utils.logging_manager:Index Boston_index already exists. It will be updated on existing table.
Successfully created vector store for Boston.
Creating vector store for Atlanta...
01-03-2024 10:39:20 WARNING[executor_utils:executor_utils.py:handle_if_not_exists:0094] Table: Atlanta_features already exists
WARNING:evadb.utils.logging_manager:Table: Atlanta_features already exists
01-03-2024 10:39:20 WARNING[create_index_executor:create_index_executor.py:_create_evadb_index:0119] Index Atlanta_index already exists. It will be updated on existing table.
WARNING:evadb.utils.logging_manager:Index Atlanta_index already exists. It will be updated on existing table.
Successfully created vector store for Atlanta.
Question (enter 'exit' to exit): which city has the highest population?
🧠 Generating subquestions...
🤑 LLM call cost: $0.0006
Traceback (most recent call last):
  File "/home/aravindh/devel/ai/rag-demystified/complex_qa.py", line 167, in <module>
    subquestions_bundle_list, cost = generate_subquestions(question=question,
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aravindh/devel/ai/rag-demystified/subquestion_generator.py", line 76, in generate_subquestions
    subquestions_pydantic_obj = SubQuestionBundleList(**subquestions_list)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aravindh/devel/ai/rag/lib64/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 4 validation errors for SubQuestionBundleList
subquestion_bundle_list.0.function
  Input should be 'vector_retrieval' or 'llm_retrieval' [type=enum, input_value='getPopulation', input_type=str]
subquestion_bundle_list.0.data_source
  Input should be 'Toronto', 'Chicago', 'Houston', 'Boston' or 'Atlanta' [type=enum, input_value='Wikipedia', input_type=str]
subquestion_bundle_list.1.function
  Input should be 'vector_retrieval' or 'llm_retrieval' [type=enum, input_value='getCityWithHighestPopulation', input_type=str]
subquestion_bundle_list.1.data_source
  Input should be 'Toronto', 'Chicago', 'Houston', 'Boston' or 'Atlanta' [type=enum, input_value='Wikipedia', input_type=str]
```

I had to apply the following patch to get this stage:
```
 rag-demystified   main U:3  git diff
diff --git complex_qa.py complex_qa.py
index 336725e..116d6db 100644
--- complex_qa.py
+++ complex_qa.py
@@ -155,7 +155,7 @@ if __name__ == "__main__":
 
     vector_stores = generate_vector_stores(cursor, wiki_docs)
 
-    llm_model = "gpt-35-turbo"
+    llm_model = "gpt-3.5-turbo"
     total_cost = 0
     while True:
         question_cost = 0
diff --git openai_utils.py openai_utils.py
index abaf187..e9bfe52 100644
--- openai_utils.py
+++ openai_utils.py
@@ -16,6 +16,7 @@ logger = logging.getLogger(__name__)
 
 OPENAI_PRICING = {
     'gpt-35-turbo': {'prompt': 0.0015, 'completion': 0.002},
+    'gpt-3.5-turbo-0613': {'prompt': 0.0015, 'completion': 0.002},
     'gpt-35-turbo-16k': {'prompt': 0.003, 'completion': 0.004},
     'gpt-4-0613': {'prompt': 0.03, 'completion': 0.06},
     'gpt-4-32k': {'prompt': 0.06, 'completion': 0.12},
diff --git requirements.txt requirements.txt
index df6523e..69ca9e4 100644
--- requirements.txt
+++ requirements.txt
@@ -1,6 +1,6 @@
 evadb[document]
-openai
-instructor
+openai==0.28.1
+instructor==0.2.11
 pydantic==2.4.0
 python-dotenv==1.0.0
 tiktoken
```
I made an attempt to [migrate the project](https://github.com/aravindhp/rag-demystified/tree/openai-1.6.1) to OpenAI 1.6.1 but ran into a similar issue.

**Comment by pchunduri6** [comment]
Hi, thanks for pointing this out. The issue arises due to the unreliability of OpenAI function calling responses. Even though we try to fix the output schema, the model responses often fail to follow our instructions.

I've made several changes to improve the reliability in the recent PR: https://github.com/pchunduri6/rag-demystified/pull/8. I've also migrated the code to OpenAI v1.x. I left the previous prompts in the code to document the prompt engineering efforts to make such pipelines work. Let me know if the updated code works.

**Comment by aravindhp** [comment]
The updated code works with this patch:

```
 rag-demystified   main → origin ↑4 {1} U:2  git diff
diff --git complex_qa.py complex_qa.py
index 2ee205a..de1b888 100644
--- complex_qa.py
+++ complex_qa.py
@@ -155,7 +155,7 @@ if __name__ == "__main__":
 
     vector_stores = generate_vector_stores(cursor, wiki_docs)
 
-    llm_model = "gpt-35-turbo"
+    llm_model = "gpt-3.5-turbo"
     total_cost = 0
     while True:
         question_cost = 0
diff --git openai_utils.py openai_utils.py
index 31846e6..2735d3f 100644
--- openai_utils.py
+++ openai_utils.py
@@ -18,6 +18,7 @@ logger = logging.getLogger(__name__)
 
 OPENAI_PRICING = {
     "gpt-3.5-turbo": {"prompt": 0.0015, "completion": 0.002},
+    "gpt-3.5-turbo-0613": {"prompt": 0.0015, "completion": 0.002},
     "gpt-3.5-turbo-16k": {"prompt": 0.003, "completion": 0.004},
     "gpt-4": {"prompt": 0.03, "completion": 0.06},
     "gpt-4-32k": {"prompt": 0.06, "completion": 0.12},
```

Thanks for fixing the issue.
